name: inowa
description: App zur Ansteuerung der iNoWa Boulderwand.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.3.1
  functional_data: ^1.2.0
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  confirm_dialog: ^1.0.4
  cloud_firestore: ^5.6.0
  uuid: ^4.5.1
  measured_size: ^1.0.0
  foundation: ^0.0.5

dev_dependencies:
  dependency_validator: ^3.1.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  rename_app: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  # Enables internationalization
  generate: true

