name: inowa
description: App zur Ansteuerung der iNoWa Boulderwand.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.9.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_reactive_ble: ^5.3.1
  functional_data: ^1.2.0
  intl: any
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.1


dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.1.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  rename_app: any

flutter:
  uses-material-design: true
  assets:
    - assets/

  # Enables internationalization
  generate: true
